all:
  hosts:
{% for item in my_hosts %}
{% if (item.ansible_host is defined) and (item.ansible_host is not none) %}
    {{ item.inventory_hostname }}:
      ansible_host: {{ item.ansible_host }}
      ip: {{ item.ansible_host }}
      access_ip: {{ item.ansible_host }}
{% endif %}
{% endfor %}
  children:
    kube_control_plane:
      hosts:
        node1:
    kube_node:
      hosts:
        node2:
        node3:
    etcd:
      hosts:
        node1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
